### ISSUE TITLE
What does this solve?

### ISSUE THREAD

**Issue by ArtiomOganesyan** [vahidvdn/nestjs-cashify#7]
Hi!
While working with NestJS what are the benefits to using nestjs-cashify over the cashify module?
Thanks 

And sorry for my ignorance =)

**Comment by vahidvdn** [comment]
Hi @ArtiomOganesyan 
This is a wrapper module for cashify. While Cashify is used for pure nodejs projects, nestjs-cashify is used for NestJS based projects. It gives you some features like dependency injection, async configuration, etc.
